spring.application.name=starter-demo

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.mvc.view.cache=false

salon.db.url=${SALON_DB_URL:jdbc:mysql://localhost:3306/salon?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
salon.db.username=${SALON_DB_USER:root}
salon.db.password=${SALON_DB_PASSWORD:password}

# https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/howto-hotswapping.html
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
server.servlet.jsp.init-parameters.development=true
